from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path
import sys
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from epicc.model.schema import Model


def _type_repr(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return node["$ref"].split("/")[-1]

    if "enum" in node:
        values = ", ".join(repr(v) for v in node["enum"])
        return f"enum[{values}]"

    if "const" in node:
        return f"const[{node['const']!r}]"

    if "anyOf" in node:
        return " | ".join(_type_repr(part) for part in node["anyOf"])

    if "oneOf" in node:
        return " | ".join(_type_repr(part) for part in node["oneOf"])

    node_type = node.get("type")
    if node_type == "array":
        return f"list[{_type_repr(node.get('items', {}))}]"

    if node_type == "object":
        additional = node.get("additionalProperties")
        if isinstance(additional, dict):
            return f"dict[str, {_type_repr(additional)}]"
        return "object"

    if isinstance(node_type, list):
        return " | ".join(str(part) for part in node_type)

    return str(node_type or "unknown")


def _field_rows(definition: dict[str, Any]) -> list[tuple[str, str, str, str]]:
    properties = definition.get("properties", {})
    required = set(definition.get("required", []))
    rows: list[tuple[str, str, str, str]] = []

    for field_name, field_node in properties.items():
        field_type = _type_repr(field_node)
        is_required = "yes" if field_name in required else "no"
        description = str(field_node.get("description", "")).replace("\n", " ").strip()
        rows.append((field_name, field_type, is_required, description))

    return rows


def _append_table(lines: list[str], rows: list[tuple[str, str, str, str]]) -> None:
    lines.append("| Field | Type | Required | Description |")
    lines.append("| --- | --- | --- | --- |")
    for name, field_type, required, description in rows:
        lines.append(
            f"| `{name}` | `{field_type}` | {required} | {description or '-'} |"
        )


def generate_schema_markdown() -> str:
    schema = Model.model_json_schema()
    defs = schema.get("$defs", {})
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    lines: list[str] = [
        "# Model Schema Reference",
        "",
        "This page is generated from `src/epicc/model/schema.py` using Pydantic JSON schema output.",
        "Do not edit this file by hand; re-run the generator script instead.",
        "",
        f"Generated at: `{generated_at}`",
        "",
        "## Root Model: `Model`",
        "",
    ]

    root_rows = _field_rows(schema)
    _append_table(lines, root_rows)

    if defs:
        lines.append("")
        lines.append("## Component Definitions")
        lines.append("")

    for def_name in sorted(defs):
        definition = defs[def_name]
        lines.append(f"### `{def_name}`")
        lines.append("")

        description = str(definition.get("description", "")).strip()
        if description:
            lines.append(description)
            lines.append("")

        rows = _field_rows(definition)
        if rows:
            _append_table(lines, rows)
        else:
            lines.append("No object fields (scalar/union definition).")

        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate docs/schema.md from Pydantic schema")
    parser.add_argument(
        "--out",
        default="docs/schema.md",
        help="Output markdown path (default: docs/schema.md)",
    )
    args = parser.parse_args()

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(generate_schema_markdown(), encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
